### ISSUE TITLE
colors hardcoded?

### ISSUE THREAD

**Issue by LFSaw** [mvgrimes/obsidian-todotxt-plugin#10]
Hello,

thanks for investing time into writing this plugin!
I just installed it and realised that you might have hardcoded the bg-colors of the widgets ("new ToDo" etc.). Since I need to use light mode, text renders almost invisible... (see attached screenshot)

![Screenshot 2023-08-14 at 19 46 44](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/75468/c9f07d9f-b24b-4642-b385-d9ffd00f116c)

**Comment by mvgrimes** [comment]
You are correct the colors are almost all hardcoded. I never considered anyone would use light mode.  :-)

Thanks for the feedback!

**Comment by mvgrimes** [comment]
v1.2.3 should use your theme's colors in most places.

**Comment by LFSaw** [comment]
thanks so much! i'll try asap.
