### ISSUE TITLE
Priority D and Default Context

### ISSUE THREAD

**Issue by heyitsfog** [mvgrimes/obsidian-todotxt-plugin#11]
First off I wanted to take the time to thank you for working on this project.

TodoTxt is amazing.

I would like the ability to be able to use priority D and have the bold icon show on the left hand side of the task for it.

Just and idea.. but

The ability to set a default Context would be nice, by that I mean adding to the todo task that did no have a context  defined the "default" Context name.  Example: All task by default are added to work unless context is defined by user input.  There is no context called default unless created by the user.  

thank you again for your wonderful work, if not another change was pushed to this project I would still use this every day.

**Comment by mvgrimes** [comment]
Adding support for priority D and some highlighting for E+ is a straightforward change. I've made the change and will deploy that as v1.3.0.

The default context is an interesting idea that will take a bit more work. Let me think about how to implement that. If you would open a separate issue to track it, that would be great.

Thanks for the feedback!
