### ISSUE TITLE
Set a default Context

### ISSUE THREAD

**Issue by heyitsfog** [mvgrimes/obsidian-todotxt-plugin#12]
Creating a second issue per request, as the first feature mentioned was completed.

The ability to set a default Context would be nice, by that I mean adding to the todo task that did not have a context defined the to a predefined “default” context. 

Example: All task by default are added to work unless context is defined by user input. There is no context called default unless created by the user.

I can’t overstate how much I enjoy using this plugin.  Thank you again.

**Comment by mvgrimes** [comment]
I think this can partially be implemented by allow the user to change the name used for the todo list with unassigned context. Currently the title "Default" is used for all todos without a context. I could make that configurable.

In the future, I can envision checkboxes in the new todo dialog to assign contexts/projects. Some of those could be configure to default to checked.
