### ISSUE TITLE
Duplicate lines due to adding many times the project name '+project_name' in the text file

### ISSUE THREAD

**Issue by Tcacestmoi** [mvgrimes/obsidian-todotxt-plugin#14]
Hello, there is an issue when you use the application intensively, It duplicates many times lines beacause in the text file it adds many times "+app +app +app" ...

**Comment by mvgrimes** [comment]
I'm not really sure why anyone would include duplicated tags, but I'm sure there is some valid use case. The next release will fix this. 

Thanks for the report.
