### ISSUE TITLE
Problems with tasks, projects and contexts in a language other than English

### ISSUE THREAD

**Issue by AGenuZ** [mvgrimes/obsidian-todotxt-plugin#15]
Hello!

1. The extension is not able to recognize contexts and projects in languages other than English. From my old todo.txt list, only those that were in English were recognized. The file encoding is UTF8. Please fix this problem in the next version.
Because now the text of tasks with contexts and projects created in another language is visible, but it is all in the "Default" column. 

2. When trying to mark a task in another language by single click on its text, the overview jumps from line to line and sometimes the task is duplicated in the output in Obsidian, but not in the file itself.
At the same time, if you edit a task by clicking on the pencil button, it will save and display perfectly. Marking a task completed via a checkbox also works fine.

Thank you in advance!

**Comment by mvgrimes** [comment]
I understand and can reproduce the problem in 1. The next release (1.3.2) should fix the issue. 

I haven't been able to reproduce the issue in 2. I'm hopeful the changes in the next release will also address that problem. If it doesn't please reopen this bug report or create a new one. It would be helpful if you could attach an example .todotxt file, and include information about the device you are using, operating system version, Obsidian version, etc.

Thanks for the bug report.
