### ISSUE TITLE
Long tasks are not moved to a new line, but to a neighboring column

### ISSUE THREAD

**Issue by AGenuZ** [mvgrimes/obsidian-todotxt-plugin#17]
_Thanks for the update to 1.3.2. The two problems I described earlier have been successfully resolved._ 

But a new one has popped up - for some reason some data is not moved to a new line, and overlaps the contents of other lines.
I noticed that this happens more often in tasks that have a long description and many specified projects and contexts. Long task descriptions without projects and contexts are normally moved to several lines.

The screenshots are attached:

![flameshot__2023 08 31__21-46-16](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/85378254/a5f8d714-a30b-4713-bf1f-7df3e60476a6)
![flameshot__2023 08 31__21-46-59](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/85378254/51611f7a-85c9-415f-82a7-ab0a98327038)
![flameshot__2023 08 31__21-48-00](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/85378254/5f4e3bc9-32f7-4461-81ac-631f4027ac3c)
![flameshot__2023 08 31__22-01-36](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/85378254/7b743aca-917a-49c6-932c-04b3d7aaf00a)

**Comment by mvgrimes** [comment]
Can you take a look at 1.3.3 to see if that fixes it?

If not, would you share a .todotxt file that has the issue. Also, what device (Windows/mac/iPhone/etc) are you using?

**Comment by AGenuZ** [comment]
> Can you take a look at 1.3.3 to see if that fixes it?
Works fine. **Thank you very much!**

**v.1.3.2**
![flameshot__2023 09 01__21-17-14](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/85378254/a2fddbad-61ce-4cb6-b2b7-dc907106f15b)

**v.1.3.3**
![flameshot__2023 09 01__21-27-52](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/85378254/a2970305-3395-4816-bea8-0610bac70e00)
