### ISSUE TITLE
Not Working on iPhone or ipad

### ISSUE THREAD

**Issue by tenebrisnox** [mvgrimes/obsidian-todotxt-plugin#18]
The plugin is working great on my desktop.

It just doesn’t work on iPhone and ipad. On both the plugin refuses to “enable” and gives the error message “Failed to load plugin todotxt”.

I’ve uninstalled and reinstalled - but it gives the same error. (I’ve not done a manual install, though.)

**Comment by mvgrimes** [comment]
iOS doesn't make this easy to debug, but it seems that there are two regex features that weren't added to iOS Safari until recently. One of which prevents the plugin from loading and the other would prevent it from displaying anything meaningful.

I've got a fix which should be released as 1.4.3 once I've done some more testing.

Thanks for the bug report.
