### ISSUE TITLE
Allow display of projects / contexts inline

### ISSUE THREAD

**Issue by harshad1** [mvgrimes/obsidian-todotxt-plugin#20]
I often write tasks with projects and contexts 'inline' as verbs and nouns:

```
(B) 2023-10-17 Tell @wife that I need to fix my +bike this afternoon
```

It would be nice if these showed up inline.

Having them show up inline _and_ called out would be fine too.

**Comment by mvgrimes** [comment]
I can see the benefit of this. Unfortunately, it isn't a particularly easy change.

I'll put it on the list of potential future features. If there are a lot of people looking for this, I'll move it up.

**Comment by Jefferderp** [comment]
+1 on this. Unfortunate it's not a simple fix. I love this plugin, but the restriction hampers my existing workflow with todo.txt.

**Comment by harshad1** [comment]
I wrote the (regex based) todo.txt parser for Markor. Let me know if you would like a second set of eyes or something else.

**Comment by Jefferderp** [comment]
I won't have time to help test in the next couple weeks, but I greatly appreciate this addition and am looking forward to it!
