### ISSUE TITLE
allow parser to pick up scheduled and start date from obsidian tasks format

### ISSUE THREAD

**Issue by pcause** [mvgrimes/obsidian-todotxt-plugin#21]
obsidian tasks uses a character to specify the scheduled date and the start date (t in todotxt).  If you can pick these up in parsing and use them in the todotxt display it will make transitioning /interoperability with the obsidian todo plugin  much easier.  since many other plugins (time ruler is one example) pick up this format, it allows alternate displays uses of the todotxt file.

**Comment by mvgrimes** [comment]
We do recognize the `t:yyyy-mm-dd` tag. If the date is in the future the task is dimmed a bit. 

![image](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/92431/ecd41275-9203-47f8-9090-de79520c8ab6)

Is there something else you are hoping for?

**Comment by mvgrimes** [comment]
I'm going to close this since I haven't heard any further. Feel free to reopen it if you would like.
