### ISSUE TITLE
if no date/priority please don't put in the []

### ISSUE THREAD

**Issue by pcause** [mvgrimes/obsidian-todotxt-plugin#22]
I may have tasks without a date priority in my todotxt file.  When you parse if you don't find these you seem to put in a [].  have an option not to.

**Comment by mvgrimes** [comment]
Can you clarify what you mean by "without a date priority"? I am not seeing the behavior you described in my testing.

**Comment by pcause** [comment]
sorry.  i meant without either a date or priority or without either.

**Comment by mvgrimes** [comment]
If I add this to my .todotxt file:
```
No priority or date +Project
```

It is displayed like this:
![image](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/92431/2e87d44d-9ee3-45ce-b053-433c767bc9a8)

Are you seeing something different?

**Comment by mvgrimes** [comment]
I'm going to close this since I haven't heard any further. Feel free to reopen it if you would like.
