### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vanarok** [mvgrimes/obsidian-todotxt-plugin#23]
> Install the plugin and put your todo file in your Obsidian vault with the .todotxt extension (ie, TODO.todotxt).

![Screenshot_2023-11-13-15-37-54-621_md obsidian](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/6105977/57fe6b74-1232-44ab-bcde-907c5a16cc6d)
![Screenshot_2023-11-13-15-37-36-466_md obsidian](https://github.com/mvgrimes/obsidian-todotxt-plugin/assets/6105977/dcbe8ade-9580-43bf-97a4-b9ba7fb2d413)

**Comment by mvgrimes** [comment]
Thanks for the bug report. Can you provide some information? What device, operating system version and Obsidian version? Does the TodoTxt config work (it should be listed under the "Community Plugins" section below the "Core Plugins" section)?

**Comment by vanarok** [comment]
Расширение файла нельзя поменять из obsidian (я менял заголовок и поэтому плагин не работал), нужно использовать другую программу, что ломает весь workflow. Это проблема obsidian, поэтому закрываю проблему.
