### ISSUE TITLE
FR: Render links 

### ISSUE THREAD

**Issue by gerroon** [mvgrimes/obsidian-todotxt-plugin#24]
Hi

It would be very nice if this plugin actually renders regular markdown links. I know these are .txt but it can maybe render links as a link so that they do not look uggly in the todos.

For instance this would be rendered as "link" `[link](https://github.com/mvgrimes/obsidian-todotxt-plugin)`

**Comment by mvgrimes** [comment]
This is similar to issued #9. I've just found a solution to that, so I think this is possible. 

In general, I'm not sure how much markdown we should support. That seems to be getting away from the simplicity of the todotxt format. I'll probably add this and a config option to enable it.

**Comment by gerroon** [comment]
Hi

Thanks for considering it, you are right that we should not mess with the original simplicity of todo.txt approach. Any kind of basic linking with simple brackets suffice for other documents.

**Comment by kmf** [comment]
I'm here for this

**Comment by mvgrimes** [comment]
I'll be releasing a new version shortly (v1.6) which implements this.
