### ISSUE TITLE
Filtering and Searching todo list

### ISSUE THREAD

**Issue by jackmcdougal** [mvgrimes/obsidian-todotxt-plugin#28]
Is there a way to filter and search other than the priority dropdown?  I tried using Obsidian's search with file:todo.todotxt but it doesn't pick anything up.   Sorry if obvious ... new to Obsidian and just learning ... Thanks!

**Comment by mvgrimes** [comment]
There really isn't a good way right now. I think I'll add a search box that can be used to filter the todo. 
Thanks for the question/request.

**Comment by jackmcdougal** [comment]
Hi!  Thanks for this feature addition!  2 Issues popped up when I updated (1 unrelated, 1 pretty critical):  1) Got a parsing error on my todo file (Obsidian wouldn't open it).  Tracked it down to having a space at the some todo lines - removing spaces fixed it.

2) SERIOUS BUG:  Editing a task while in SEARCH mode will delete all tasks in your todo that aren't in the search term!

**Comment by mvgrimes** [comment]
Thanks for reporting this! My apologies and I hope you were able to recover your Todo file.
I'm releasing v2.0.3 with a fix now.

**Comment by mvgrimes** [comment]
I'm curious about the space that wouldn't let you open the file. If you have an example, I'd appreciate seeing it.
