### ISSUE TITLE
Failed to install plugin - Mac M1

### ISSUE THREAD

**Issue by ngrlt** [mvgrimes/obsidian-todotxt-plugin#29]
Hi and thanks for your great work !

I'm trying to install the plugin from the community plugin list in Obsidian 1.5.12 running on a Mac M1 with Mac OS Sonoma but I get an error message saying "Failed to install plugin "TodoTxt". 

Any idea what can be the issue here ?

Thanks

**Comment by mvgrimes** [comment]
Hi @Henrydice, 

It seems the Obsidian is trying to install an unreleased version of the plugin (dev-v2.0.0). The production branch of that version will be released shortly. That should fix the issue.

Thanks for letting me know.
