### ISSUE TITLE
Change default action when clicking the name of a task

### ISSUE THREAD

**Issue by Henrydice** [mvgrimes/obsidian-todotxt-plugin#33]
Hi,

By default, clicking the name of a task marks it as complete, but I personally find it a bit misleading and confusing. What about changing the default behavior from marking as complete to just editing it ?

That way, if we want to mark a task as complete we can still click the checkbox but we can also edit the task by clicking on its name. 

Thanks again !

**Comment by mvgrimes** [comment]
I think clicking the description should result in the same action as clicking the checkbox, but I could add support for long click/press to open the edit dialog. I've been meaning to do this to improve the mobile experience. 

Thoughts? If lot's of users find this confusing, I could probably make this configurable.

**Comment by mvgrimes** [comment]
The solution in v2.1 isn't working very well, particularly on mobile devices. I'm going to remove the click/tap on the label. You can still long press the label to edit, but now only the checkbox will toggle the todo.
