### ISSUE TITLE
QoL improvements`

### ISSUE THREAD

**Issue by alexander-newton** [mvgrimes/obsidian-todotxt-plugin#34]
Hi @mvgrimes ,

Thanks for much for your work on this plugin. It's great for my use case.

I have a couple of QoL suggestions which would improve the quality of the plugin for me; though, of course, it may not suit your needs as well.

1. When clicking to edit a task using the plugin, it interprets this also as "completing" the task and opens up the edit dialog. My expected behaviour would be that is doesn't complete the task too, but only opens up the edit dialog.
2. When clicking a link in a task on the plugin page, it also completes the task. When I click a link, the expected behaviour is to just open the link and not complete the task.
3. When resizing the window or tab that holds the open .todotxt file the plugin always stays at three columns, the number of columns should vary in response to the size of the window - there must be CSS already written that completes this for you. 
4. Give the option to also not separate out tasks by project/context, so it's just one list.

Thanks again, and let me know your thoughts. In summer I may have time to have a go at these myself, though I've never used typescript before.

Alex

**Comment by mvgrimes** [comment]
Glad your enjoying the plugin, and I appreciate the thanks.

Your 1 and 2 are related to issue #33. Unfortunately, the way I addressed that doesn't really work that well (particularly on mobile devices). I'm going to release a new version that removes the click/tap to toggle the Todo from the label/description. You can still edit the Todo by long pressing, but toggling will now only happen with clicking the checkbox. Hopefully, this will be intuitive and eliminate the issues you and others have identified.

For number 3, the columns should already be adjusting base on the screen width. Looking at it again, I think the breakpoints are too small, so the columns are added while the screen is still too small. I'm going to adjust the breakpoints so the screen will need to be larger before add columns. If you aren't seeing the number of columns adjusting, please let me know what device you are using.

Number 4 seems like a good idea but will take a little more work. I'll look into adding that when I have more time. A PR would be welcome, and I'd be happy to help with the typescript if you just implement in plain javascript. 

If you could write-up 4 as a separate issue that would be great. It is easier to manage the issues if each is broken out.
