### ISSUE TITLE
export/import obsidian tasks format

### ISSUE THREAD

**Issue by pcause** [mvgrimes/obsidian-todotxt-plugin#4]
what would be great is to be able to read a todo.txt file and create an obsidian tasks formatted note and to export the items from an obsidian formatted tasks to a todo.txt file.  being able to use an obsidian query to select items to export would be terrific.

**Comment by mvgrimes** [comment]
This seems like a different approach to handling TodoTxt files from the one taken by this plugin. My initial reaction is that it would be more suitable to implement in a separate plugin. That said, I'm open to additional discussion and pull requests.

**Comment by mvgrimes** [comment]
I'm going to close this, but feel free to re-open it if you would like to continue the conversation.
