### ISSUE TITLE
[Feature Request] Custom File Extension

### ISSUE THREAD

**Issue by Cicero24C** [mvgrimes/obsidian-todotxt-plugin#5]
I want to use this Obsidian plugin to manage my existing `todo.txt` files. Some of them can not be renamed to `.todotxt` extension. I think it is better to provide an option to custom file extension, or just choose some specific files, to be managed by this plugin.

**Comment by mvgrimes** [comment]
I can see why this would useful, but it would treat all `.txt` files as TodoTxt files (which I why I chose `.todotxt`). I'm adding it to the repo under the [feat/add-exts](https://github.com/mvgrimes/obsidian-todotxt-plugin/tree/feat/addl-exts) branch. I'd welcome additional comments.

**Comment by Cicero24C** [comment]
> but it would treat all `.txt` files as TodoTxt files

So can we step a little lower? We don't handle all `.txt` files, but only some specific files. Say, I have two TodoTxt files: `t1.txt`, `t2.todo`. And this plugin would match only the file name of `t1.txt` and `t2.todo`.

Additionally, is it OK to add a switch:

- on: handle all `txt` files;
- off: handle only the files we choose.

Ha, I think it'll be better to have a command as "let current files be handled by todotxt" when I press `ctrl + p`.

Thanks for you work.

**Comment by mvgrimes** [comment]
Good idea, but that isn't easy to implement. The way Obsidian designed their plugin system, the plugin registers the file extensions that it handles rather than individual files.

I'm going to release a version of the plugin with this implemented but marked as "experimental". We'll see how that works.
