### ISSUE TITLE
'not parsed: ' Error in .todotxt files modified with external editor.

### ISSUE THREAD

**Issue by LunarMagic69** [mvgrimes/obsidian-todotxt-plugin#6]
# Problem Statement

When ```.todotxt``` file is saved using another TodoTxt-aware editor and then opened in Obsidian (with the Obsidian-TodoTxt-Plugin) the items are shown all in the ```+Default``` group pre-pended with the text ```not parsed: ```.

# Environment

  *  Windows 11
  *  Obsidian for Windows

# Research

I was able to edit the individual lines in Obsidian removing the text ```not parsed: ``` and the items returned to the normal behavior, with the context and project data intact.

Opening the .todotxt file in a plain-text editor revealed that the plugin-saved file had the UNIX EOL characters (/n), while the file saved by the external editor had Windows EOL characters (/r/n).

Globally switching back to the UNIX format seemed to 'fix' the entire file all at once.

# Proposed Solution

  *  Allow JavaScript/TypeScript to interact with text files using the Windows EOL characters (if possible).
  *  On reload/refresh of modified .todotxt file, automatically strip out the Carriage Return (/r) character, returning the file to the UNIX-compliant format.

**Comment by mvgrimes** [comment]
A key requirement for this plugin is that it allow users to interact with their TodoTxt files with other editors/tools, so this seems like an important bug. I'll add code to recognizing the file's EOL format and preserve it.

Thanks for the thorough bug report.
