### ISSUE TITLE
A new "by-context" visualization to switch to when needed 

### ISSUE THREAD

**Issue by mastro35** [mvgrimes/obsidian-todotxt-plugin#7]
I'd like to have the ability to switch the default view to a view that shows my tasks grouped by context and with the project name as a task detail'.

In this way, I could use the context to specify which is the GTD list the task belong (next actions, waiting for etc...) and toggle the visualization of my system between the default by-project view and the by-context view.

Thanks for you time and for this great plugin.

**Comment by mvgrimes** [comment]
Sounds like a good idea. I've implemented it in v1.2.0.

The default grouping can be specified in the plugin's configuration and it can be changed on the todo page with a dropdown.

Thanks for the idea and the feedback.
