### ISSUE TITLE
Add linking support

### ISSUE THREAD

**Issue by Gamer-Kold** [mvgrimes/obsidian-todotxt-plugin#9]
I would like to link to my notes within my todo list; is that possible?

**Comment by mvgrimes** [comment]
So a todo could look like:

    (A) Review the [[New Project]] +Work

and `New Project` would be a link to that page in your vault, correct?

Sounds reasonable, but I haven't looked into how Obsidian handles links. Seems like it should be possible.

**Comment by Gamer-Kold** [comment]
Yes essentially.

I'm not too sure myself; not a big web developer. But the 
`generateMarkdownLinks` function in the obsidian API seems promising, (though it seems linked to the file manager).

Judging from how the documentation talks about links, I'd assume links are just anchor tags in the UI, right?
